[package]
name = "hyper-openssl"
version = "0.2.6"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Hyper SSL support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
documentation = "https://docs.rs/hyper-openssl/0.2.6/hyper_openssl"
readme = "README.md"
exclude = ["test/*"]

[dependencies]
antidote = "1.0"
hyper = "0.10"
time = "0.1.17"
openssl = {path ="/Users/sgujral/Desktop/parallel_cert/hyper-openssl/rust-openssl/openssl", version="0.9.10"}
